name: Deploy Portfolio
on:
  push:
    branches: [main]

permissions:
  pages: write
  id-token: write

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Pages
        uses: actions/configure-pages@v3

      - name: Build Site
        run: |
          mkdir -p public
          cp -R simplefolio/* public/
          cp -R simplefolio/.[^.]* public/ 2>/dev/null || true

      - name: Upload artifact
        uses: actions/upload-pages-artifact@v2
        with:
          path: 'public'

      - name: Deploy
        uses: actions/deploy-pages@v2
