name: Deploy Portfolio
on:
  push:
    branches: [main]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        
      - name: Setup Pages
        uses: actions/configure-pages@v3
        
      - name: Prepare files
        run: |
          mkdir -p public
          cp -R src/* public/
          cp -R src/.* public/ 2>/dev/null || true
          
      - name: Upload artifact
        uses: actions/upload-pages-artifact@v2
        with:
          path: 'public'
          
      - name: Deploy to GitHub Pages
        uses: actions/deploy-pages@v2
